flask_app/stats/routes.py
from flask import Flask, Blueprint, redirect, url_for, render_template

stats = Blueprint("stats", __name__)


@stats.route('/', methods=["GET", "POST"])
def index():
    return render_template("index.html")

flask_app/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required, login_user, logout_user
import base64
from io import BytesIO
from .. import bcrypt
from werkzeug.utils import secure_filename
from ..forms import RegistrationForm, LoginForm, UpdateUsernameForm, UpdateProfilePicForm
from ..models import User
from random import randint

users = Blueprint("users", __name__)

""" ************ User Management views ************ """


# TODO: implement
@users.route("/signup", methods=["GET", "POST"])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for("stats.index"))
    form = RegistrationForm()
    if request.method == "POST":
        if form.validate_on_submit():
            user = User(
                first_name=form.first_name.data,
                last_name=form.last_name.data,
                username=form.username.data,
                email=form.email.data,
                password=bcrypt.generate_password_hash(form.password.data)
            )
            user.save()
            return redirect(url_for("users.login"))
    return render_template("signup.html", form=form)


# TODO: implement
@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("stats.index"))
    form = LoginForm()
    if request.method == "POST":
        if form.validate_on_submit():
            user = User.objects(username=form.username.data).first()
            if user is not None and bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user)
                return redirect(url_for("stats.index"))
            else:
                flash("Login failed. Check your username and/or password")
    return render_template("login.html", form=form)



# TODO: implement
@users.route("/logout")
@login_required
def logout():
    logout_user()
    return render_template("logout.html")


@users.route("/settings", methods=["GET", "POST"])
@login_required
def settings():
    update_username_form = UpdateUsernameForm()
    update_profile_pic_form = UpdateProfilePicForm()
    if request.method == "POST":
        if update_username_form.submit_username.data and update_username_form.validate():
            # TODO: handle update username form submit
            User.objects(username=current_user.username).update(
                set__username=update_username_form.username.data
            )
            logout_user()
            return redirect(url_for("users.settings"))
        update_username_form.username.data = ""

        if update_profile_pic_form.submit_picture.data and update_profile_pic_form.validate():
            # TODO: handle update profile pic form submit
            image = update_profile_pic_form.picture.data
            filename = secure_filename(image.filename)
            content_type = f'images/{filename[-3:]}'

            if current_user.profile_pic is None:
                current_user.profile_pic.put(
                    image.stream, 
                    content_type=content_type
                )
            else:
                current_user.profile_pic.replace(
                    image.stream,
                    content_type=content_type
                )
            current_user.save()
            return redirect(url_for("users.settings"))

    # TODO: handle get requests
    user = User.objects(username=current_user.username).first()
   
    greeting = random_greeting() + current_user.username + '!'
    image = None
    if user.profile_pic:
        bytes_im = BytesIO(user.profile_pic.read())
        image = base64.b64encode(bytes_im.getvalue()).decode()
    
    return render_template(
        "settings.html", 
        greeting=greeting, 
        update_username_form=update_username_form,
        update_profile_pic_form=update_profile_pic_form,
        image=image
    )
    
def random_greeting():
    arr = [
        "Welcome back, ", 
        "Howdy, ",
        "Good to see you, ",
        "Hello, "
    ]
    return arr[randint(0, len(arr) - 1)]

flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      rel="stylesheet"
      href="{{url_for('static',filename='styles.css')}}"
    />
    <!-- {% if title %} -->
        <!--<title>{{ title }}</title> -->
    <!--{% else %} -->
        <title> {% block title %} Soccer Visualizer {% endblock %}</title>
    <!--{% endif %}-->
</head>
<body>
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}
</body>
</html>

flask_app/templates/header.html
{% extends "base.html" %} {% block header %}
<nav class="navbar flex w-full justify-between z-40">
    <a class="m-5 navlink" href="{{ url_for('stats.index') }}">
        <span class="hidden sm:block">Home</span>
        <span class="block sm:hidden">Home</span>
    </a>
    {% if current_user.is_authenticated %}
    <div class="flex">
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.settings') }}">Settings</a>
        <a class="my-5 mr-5 ml-0 navlink !bg-red-400/20 hover:!bg-red-500/50 !text-red-400 hover:!text-red-300" href="{{ url_for('users.logout') }}">Logout</a>
    </div>
    {% else %}
    <div class="flex">
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.login') }}">Login</a>
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.signup') }}">Sign Up</a>
    </div>
    {% endif %}
</nav>
{% block content %}{% endblock %}{% endblock %}

flask_app/templates/index.html
<!--
<div id="wg-api-football-games"
     data-host="v3.football.api-sports.io"
     data-key=""
     data-date=""
     data-league=""
     data-season=""
     data-theme=""
     data-refresh="15"
     data-show-toolbar="true"
     data-show-errors="false"
     data-show-logos="true"
     data-modal-game="true"
     data-modal-standings="true"
     data-modal-show-logos="true">
</div>
<script
    type="module"
    src="https://widgets.api-sports.io/2.0.3/widgets.js">
</script>
-->
{% extends "header.html" %}

flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h2 class="text-2xl font-bold text-center">Log In</h2>
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3 text-center my-2">
    If you don't have an account, <a class="text-blue-400 duration-150 hover:text-blue-200 underline" href="{{ url_for('users.signup') }}">register here</a>.
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">

    {# show flashed messages if an authentication error occurs #}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class="error" role="alert">
                    <span>{{ message }}</span>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <form class="review-form" method="POST" action="">
        {{ form.csrf_token }}
        <div class="form-group review-input">
            {{ form.username.label }}
            {{ form.username(class="form-content") }}
            {% if form.username.errors %}
            <div class="error" role="alert">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.password.label }}
            {{ form.password(class="form-content") }}
            {% if form.password.errors %}
            <div class="error" role="alert">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ form.submit(class="review-button") }}
    </form>

</div>
{% endblock %}

flask_app/templates/logout.html
<p> Logging out {{ current_user.first_name }}</p>

flask_app/templates/settings.html
{% extends "header.html" %}

{% block title %}Settings{% endblock %}
{% block content %}
    <div>
        <h1>Settings</h1>
        <h1>Account</h1>
    </div>
{% endblock %}

flask_app/templates/signup.html
{% extends "header.html" %}
{% block content %}
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h2 class="text-2xl font-bold text-center">Sign Up</h2>
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3 text-center my-2">
    If you already have an account, <a class="text-blue-400 duration-150 hover:text-blue-200 underline" href="{{ url_for('users.login') }}">login here</a>.
</div>
<!-- Registration Form: -->
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">

    <form class="review-form" method="POST" action="">
        {{ form.csrf_token }}
         <div class="form-group review-input">
            {{ form.first_name.label }}
            {{ form.first_name(class="form-content") }}
            {% if form.first_name.errors %}
            <div class="error" role="alert">
                {% for error in form.first_name.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
         <div class="form-group review-input">
            {{ form.last_name.label }}
            {{ form.last_name(class="form-content") }}
            {% if form.last_name.errors %}
            <div class="error" role="alert">
                {% for error in form.last_name.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.username.label }}
            {{ form.username(class="form-content") }}
            {% if form.username.errors %}
            <div class="error" role="alert">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.email.label }}
            {{ form.email(class="form-content") }}
            {% if form.email.errors %}
            <div class="error" role="alert">
                {% for error in form.email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.password.label }}
            {{ form.password(class="form-content") }}
            {% if form.password.errors %}
            <div class="error" role="alert">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.confirm_password.label }}
            {{ form.confirm_password(class="form-content") }}
            {% if form.confirm_password.errors %}
            <div class="error" role="alert">
                {% for error in form.confirm_password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        
        {{ form.submit(class="review-button") }}
    </form>

</div>

{% endblock %}